### PR TITLE
adding updated JS file with input validation code for questions

### PR DESCRIPTION
**Pull request by dombrown95**
Updated JS code to validate user input against predetermined ranges. Provides error feedback if input isn't included in range.

Screenshot of feedback - 

Screenshot 2023-12-06 210336

### CODE REVIEW

**Comment by ph8tfunk** [comment]
tested inputs. only accepts input within boundary. works well.
could the allergy input only accept text and not numeric.

**Comment by dombrown95** [comment]
Committed new JS code - 

- Q3 will now send the invalid feedback message if the user enters numeric input 
- Q1 function slightly altered to provide feedback on every input outside of predetermined ranges, rather than just the first input identified

**Comment by ph8tfunk** [comment]
all good.

**Comment by ph8tfunk** [comment]
looks good.

**Review by ph8tfunk — APPROVED** [review]
approved

**Pull request merged**
